version: "3.10"

volumes:
  app_validator:
  static_volume:

networks:
    djangonetwork:
        driver: bridge

services:
      
    nginx:
        image: nginx_container
        build:
            context: compose/nginx
            dockerfile: Dockerfile
        restart: on-failure
        links:
            - app:app
        ports:
            - "${NJINX_HOST_PORT}:80"
        expose:
            - "${NJINX_HOST_PORT}"
        volumes:
            - static_volume:/app/static
        networks:
            - djangonetwork
    database:
        container_name: postgres_container
        image: 'postgres:latest'
        restart: always
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - DATABASE_URL=${DATABASE_URL}
        ports:
            - "8001:5432"
        expose:
            - "5432"
        volumes:
            - ./data/db:/var/lib/postgresql/pgdat
        networks:
            - djangonetwork
    app:
        image: validator_container
        restart: always
        build:
            context: .
            dockerfile: compose/app/Dockerfile
        depends_on:
            - database
        volumes:
            - app_validator:/app/ads_validator
            - static_volume:/app/static
        env_file:
            - ./compose.env
        expose:
            - "8081"
        ports:
            - "8081:8081"
        links:
            - "database"
            - "database:database_link"
        networks:
            - djangonetwork
    